language: python
python:
  - "3.6"

install:
  - mkdir /etc/fofo
  - wget https://olivetree.oss-cn-hangzhou.aliyuncs.com/fofo && chmod +x fofo
  - wget https://olivetree.oss-cn-hangzhou.aliyuncs.com/config.toml -O /etc/fofo/config.toml
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coverage
  - pip install pytest-cov

before_script:
  # - mkdir /consul_data
  - nohup ./fofo &
  - sleep 5

services:
  - redis-server

script:
  - pytest --cov=laka -s test_unit.py

after_success:
  - codecov